#!/bin/bash

UNIFIED_PROJECT_TOOL_VERSION="1.0.0"

EXECUTABLE_INSTALL_DIR="${EXECUTABLE_INSTALL_DIR:-/usr/local/bin}"
PROJECTS_INSTALL_DIR="${PROJECTS_INSTALL_DIR:-$HOME/.unified-project-tool}"

# Help message
function display-help-message {
    echo "Usage: $0 [MODE] [PROJECT TYPE] [PROJECT NAME]"

    echo ""
    echo "Modes:"
    echo "- bootstrap: Bootstrap a project with the specified type and name"
    echo "- install:   Install unified-project-tool to the paths defined by EXECUTABLE_INSTALL_DIR"
    echo "             and PROJECTS_INSTALL_DIR (see defaults in the executable: $0)"
    echo "- help:      Show this help message"
    echo ""

    # List available project types (if installed)
    if [ -d $PROJECTS_INSTALL_DIR ]; then
        echo "Available project types:"
        for d in $PROJECTS_INSTALL_DIR/*/; do
            echo "- $(basename -- $d)"
        done
    fi

    echo ""
    echo "unified-project-tool v$UNIFIED_PROJECT_TOOL_VERSION"
    echo "Copyright (c) 2024 jarvarvarvis"
}

# Get run mode
run_mode="$1"

# Show help message in help mode
if [ "$run_mode" = "help" ]; then
    display-help-message
    exit
fi

# Install mode
if [ "$run_mode" = "install" ]; then
    # Install unified-project-tool executable
    echo "Installing unified-project-tool to $EXECUTABLE_INSTALL_DIR..."
    sudo cp unified-project-tool $EXECUTABLE_INSTALL_DIR/

    # Install project templates
    echo "Installing projects to $PROJECTS_INSTALL_DIR..."
    mkdir -p $PROJECTS_INSTALL_DIR
    cp -r projects/* $PROJECTS_INSTALL_DIR/

    echo ""
    echo "Done!"
fi

# Project bootstrap function
function bootstrap-project {
	project_name="$1"
	project_type="$2"
	bootstrapped_file="$3"
	bootstrap_args="${@:4} PROJECT_NAME=$project_name"

	# Create project
	mkdir $project_name
	cp -r $PROJECTS_INSTALL_DIR/$project_type/** $project_name/

	# Substitute project args in the bootstrapped file
	for def in $bootstrap_args; do
        def_split=(${def//=/ })
        def_key=${def_split[0]}
        def_value=${def_split[1]}
        echo "[$project_type] Set build value: $def_key -> $def_value"
        sed -i "s/<<@$def_key@>>/$def_value/g" "$project_name/$bootstrapped_file"
	done
}

# Bootstrapping mode
if [ "$run_mode" = "bootstrap" ]; then
    # Get args
    project_type="$2"
    project_name="$3"

    if [ -z "$project_type" ]; then
        display-help-message
        exit
    fi

    if [ -z "$project_name" ]; then
        display-help-message
        exit
    fi

    bootstrap_args_file=$PROJECTS_INSTALL_DIR/$project_type.bootstrap-args

    echo "Got bootstrap args file: $bootstrap_args_file"

    if [ -f "$bootstrap_args_file" ]; then
        echo "Creating $project_type project in $(pwd)"

        # Execute bootstrap args file and pass result to the bootstrap function
        bootstrap-project $project_name $(exec $bootstrap_args_file)
    else
        echo "Unknown project type: \"$project_type\"!"
    fi
fi
