#!/bin/bash

UNIFIED_PROJECT_TOOL_VERSION="1.0.0"
UNIFIED_PROJECT_TOOL_AUTHOR="jarvarvarvis"

EXECUTABLE_INSTALL_DIR="/usr/local/bin/"
PROJECTS_INSTALL_DIR="$HOME/.unified-project-tool/"

# Installing
if [ "$1" = "install" ]; then
    echo "Installing unified-project-tool to $EXECUTABLE_INSTALL_DIR..."

    # Copy unified-project-tool executable
    sudo cp unified-project-tool $EXECUTABLE_INSTALL_DIR
    echo ""
    
    echo "Installing projects to $PROJECTS_INSTALL_DIR..."

    # Copy project templates
    mkdir -p $PROJECTS_INSTALL_DIR
    sudo cp -r projects/* $PROJECTS_INSTALL_DIR
    echo ""
    
    echo "Done! Press any key to continue..."
    read
    exit
fi

# Help message
function display-help-message {
    echo "Usage: $0 [PROJECT TYPE] [PROJECT NAME]"

    echo ""
    echo "Unified project tool v$UNIFIED_PROJECT_TOOL_VERSION"
    echo "Originally written by $UNIFIED_PROJECT_TOOL_AUTHOR"
}

# Project bootstrapping
function bootstrap-project {
	project_name="$1"
	project_type="$2"
	bootstrapped_file="$3"
	bootstrap_args="${@:4} PROJECT_NAME=$project_name"

	# Create project
	mkdir $project_name
	cp -r $PROJECTS_INSTALL_DIR/$project_type/** $project_name/

	# Substitute project args in the bootstrapped file
	for def in $bootstrap_args; do
        def_split=(${def//=/ })
        def_key=${def_split[0]}
        def_value=${def_split[1]}
        echo "[$project_type] Set build value: $def_key -> $def_value"
        sed -i "s/<<@$def_key@>>/$def_value/g" "$project_name/$bootstrapped_file"
	done
}

# Get args
project_type="$1"
project_name="$2"

if [ -z "$project_type" ]; then
    display-help-message
    exit
fi

if [ -z "$project_name" ]; then
    display-help-message
    exit
fi

bootstrap_args_file=$PROJECTS_INSTALL_DIR/$project_type.bootstrap-args

echo "Got bootstrap args file: $bootstrap_args_file"

if [ -f "$bootstrap_args_file" ]; then
	echo "Creating $project_type project in $(pwd)"
	bootstrap-project $project_name $(bash $bootstrap_args_file)
else
	echo "Unknown project type: \"$project_type\"!"
fi
